### ISSUE TITLE
No se asigna evento al reservar

### ISSUE THREAD

**Issue by arejula27** [UNIZAR-30249-2022-noname/CalendarWebClient#14]
Al crear una reserva no pregunta por el evento y durante toda la ui se muestra dicho dato, necesario que se añada. Un pop up sería una buena opción. Mirar [modal](https://ant.design/components/modal/)

**Comment by dolansete** [comment]
Lo he hecho con un Input directo debajo de la tabla, para no molestar con un pop up aunque mole
